library(ROCR)
par<-read.csv("parole.csv")
str(par)
table(par$violator)
par$male<-as.factor(par$male)
par$race<-as.factor(par$race)
par$state<-as.factor(par$state)
par$crime<-as.factor(par$crime)
table(par$state)

str(par$male)
str(par)
summary(par)
summary(par$race)
summary(par$male)
set.seed(144)
library(caTools)
split<-sample.split(par$violator,SplitRatio = 0.7)
par_train<-subset(par,split==TRUE)
par_test<-subset(par,split==FALSE)
par_model<-glm(violator~.,data=par_train,family = binomial)
summary(par_model)
par_1<-predict(par_model,newdata=par_train,type="response")
par_ro<-prediction(par_1,par_train$violator)
par_roc<-performance(par_ro,'tpr','fpr')
plot(par_roc,colorize=TRUE,print.cutoffs.at=seq(0,1,0.1),text.adj=c(-2,1.7))


par_pred<-predict(par_model,newdata=par_test,type="response")
table(par_test$violator,par_pred>=0.5)
par2<-prediction(par_pred,par_test$violator)
auc=as.numeric(performance(par2,"auc")@y.values)
auc
summary(par_pred)
table(par_test$violator)
